package common;

/**
 * User: allen
 * Date: 12/2/13
 * Time: 6:00 PM
 */
public class Tuple<X, Y> {
    public final X x;
    public final Y y;

    public Tuple(X x, Y y) {
        this.x = x;
        this.y = y;
    }

    //generated by intellij
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;

        Tuple tuple = (Tuple) o;

        if (!x.equals(tuple.x))
            return false;
        if (!y.equals(tuple.y))
            return false;

        return true;
    }
}